//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostAndFound
{
    using System;
    using System.Collections.Generic;
    
    public partial class LostItems
    {
        public string itemID { get; set; }
        public string ComanyName { get; set; }
        public string photoLocation { get; set; }
        public string colors { get; set; }
        public string itemType { get; set; }
        public string lostDate { get; set; }
        public string location { get; set; }
        public string description { get; set; }
    }
}
