//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostAndFound
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public string matchID { get; set; }
        public string comapnyItemID { get; set; }
        public string itemID { get; set; }
        public string matchStatus { get; set; }
    }
}
