//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyItems()
        {
            this.Matches = new HashSet<Matches>();
        }
    
        public int itemId { get; set; }
        public Nullable<int> serialNumber { get; set; }
        public string contactName { get; set; }
        public string contactPhone { get; set; }
        public string companyName { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Items Items { get; set; }
        public virtual FoundItems FoundItems { get; set; }
        public virtual LostItems LostItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matches> Matches { get; set; }
    }
}
