//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerHost.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyUsers
    {
        public string companyName { get; set; }
        public string fbProfileId { get; set; }
        public bool isManager { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual User User { get; set; }
    }
}
