//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerHost.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lostAndFoundDbEUEntities : DbContext
    {
        public lostAndFoundDbEUEntities()
            : base("name=lostAndFoundDbEUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<CompanyItems> CompanyItems { get; set; }
        public virtual DbSet<FacebookGroups> FacebookGroups { get; set; }
        public virtual DbSet<FBItem> FBItem { get; set; }
        public virtual DbSet<FoundItems> FoundItems { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<LostItems> LostItems { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
