//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyItems
    {
        public int itemId { get; set; }
        public Nullable<int> serialNumber { get; set; }
        public string contactName { get; set; }
        public string contactPhone { get; set; }
        public string companyName { get; set; }
    }
}
