//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        public Companies()
        {
            this.CompanyItems = new HashSet<CompanyItems>();
            this.FacebookGroups = new HashSet<FacebookGroups>();
        }

        public Companies(string userName, string companyName, string phone)
        {
            this.userName = userName;
            this.companyName = companyName;
            this.phone = phone;
        }

        public string userName { get; set; }
        public string companyName { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<CompanyItems> CompanyItems { get; set; }
        public virtual ICollection<FacebookGroups> FacebookGroups { get; set; }
        public virtual User User { get; set; }
    }
}
