//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LostAndFoundDBEntities : DbContext
    {
        public LostAndFoundDBEntities()
            : base("name=LostAndFoundDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> User { get; set; }
        public DbSet<Companies> Companies { get; set; }
        public DbSet<CompanyItems> CompanyItems { get; set; }
        public DbSet<FacebookGroups> FacebookGroups { get; set; }
        public DbSet<FBItem> FBItem { get; set; }
        public DbSet<FoundItems> FoundItems { get; set; }
        public DbSet<Items> Items { get; set; }
        public DbSet<LostItems> LostItems { get; set; }
        public DbSet<Table> Table { get; set; }
    }
}
