//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int matchID { get; set; }
        public int companyItemId { get; set; }
        public int itemID { get; set; }
        public string matchStatus { get; set; }
    }
}
